### ISSUE TITLE
401 Unauthorized - by connecting to Strava API

### ISSUE THREAD

**Issue by vierzwerge** [grafana/strava-datasource#62]
After updating the version from 1.3 to 1.5 I'm not able to connect to Strava API anymore.

I always get the error message: "Cannot connect to Strava API: Token exchange failed: 401 Unauthorized" by clicking "Save & Test"  in the "Data Source / Strava" section.
And a short message appears: "Token exchange failed"

I also updated the parameter GF_STRAVA_DS_DATA_PATH as mentioned in the plugin description (and made the folder readable for grafana). But without any success.

In the logfile by restarting the grafana server these messages appear (don't know if this is the problem ... ) :
"Could not read environment variable" variable=GF_STRAVA_DS_DATA_PAT"
"Using default data path" path=/usr/share/grafana/.cache/strava-datasource"

With version 1.3 everything was ok.

Thank you for your support

**Comment by RLutsch** [comment]
I have the same issue, when I add the strava datasource in grafana it shows success and I got it to work briefly but stopped again. 

When I check the logs I see error 401 Unautherized and the dashboards don't load.

**Comment by RLutsch** [comment]
so fixed it, to get it to work, whatch the logs in grafana then hit the save and test button a few times till it registers

**Comment by beagle80** [comment]
Same problem here with version 1.5 (1.3 was ok):
"Cannot connect to Strava API: Token exchange failed: 401 Unauthorized"

**Comment by alexanderzobnin** [comment]
Yes, this is a bug, unfortunately. I'm working on fix.

**Comment by hopsor** [comment]
I've just updated the plugin, restarted my instance and readded the data source and still experiencing the same 401 issue :-(

**Comment by beagle80** [comment]
I've updated the plugin and  was able to connect:
'Data source is working. Authenticated as XXX XXX'.
But if I re-import the Dashboard I get:
'Error status: 401 Unauthorized'
Thank you.

**Comment by hopsor** [comment]
yes, exactly the same issue I have

**Comment by vierzwerge** [comment]
I updated the plugin and now everything works for me :)

**Comment by vierzwerge** [comment]
I only added the datasource with OAuth (not with "Refresh Token"). And this works for me
![image](https://user-images.githubusercontent.com/54344126/189415224-68b02681-2e8a-415a-b3e0-9743a6860301.png)

**Comment by hopsor** [comment]
Will try that, thanks!

>

**Comment by wilmington** [comment]
I'm still seeing the issue with grafana cloud and plugin version 1.5.1
```
status:500
statusText:""
data:Object
error:"Internal Server Error"
message:"Error status: 401 Unauthorized"
config:Object
url:"api/datasources/24/resources/strava-api"
method:"POST"
headers:Object
data:Object
retry:0
hideFromInspector:true
message:"Error status: 401 Unauthorized"
```

**Comment by NeoPrint3D** [comment]
Any new updates
